classDiagram
	class Summer_terrain
	class Winter_background
	class Level2
	Level2 <|-- Summer_background
	Level2 <|-- Summer_terrain
	Level2 <|-- Character
	Level2 <|-- Collectable_coin
	class Base_level
	Base_level: +pause_menu()
	Base_level <|-- Winter_background
	Base_level <|-- Winter_terrain
	Base_level <|-- Character
	class Level1
	Level1 <|-- Base_level
	Level1 <|-- Collectable_coin
	Level1 <|-- Skeleton
	Level1 <|-- Kill_area
	Level1 <|-- Next_level_area
	Level1 <|-- Pause_menu
	class Summer_background
	class Godot_intro
	class Ending_screen
	class Ending_background
	class Main_menu
	Main_menu <|-- Menu_background
	class Menu_background
	class Transition_screen
	Transition_screen: +fade_in()
	class Pause_menu
	class Hud
	class Skeleton
	Skeleton <|-- Base_enemy
	class Base_enemy
	Base_enemy: +update_health()
	class Character
	Character: +disable()
	Character: +next_level()
	Character: +update_health()
	Character: +is_player_alive()
	class Collectable_component
	class Collectable_coin
	Collectable_coin <|-- Collectable_component
	class Winter_terrain
	class Fall_effect
	Fall_effect <|-- Base_effect
	class Run_effect
	Run_effect <|-- Base_effect
	class Base_effect
	class Kill_area
	class Next_level_area
